[versions]
coroutines = "1.10.1"
hiveMqtt = "1.3.5"
kotest = "5.9.1"
kotlin = "2.1.10"

[libraries]
arrow = { module = "io.arrow-kt:arrow-core", version = "2.0.1" }
arrow-coroutines = { module = "io.arrow-kt:arrow-fx-coroutines", version = "2.0.1" }
hive-mqtt = { module = "com.hivemq:hivemq-mqtt-client", version.ref = "hiveMqtt" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-rx2 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-rx2", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

[bundles]
kotest-common = [
    "kotest-assertions-core",
    "kotest-framework-engine",
]

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotest-multiplatform = { id = "io.kotest.multiplatform", version.ref = "kotest" }
dokka = "org.jetbrains.dokka:2.0.0"
gitSemVer = "org.danilopianini.git-sensitive-semantic-versioning-gradle-plugin:4.0.2"
kotlin-qa = "org.danilopianini.gradle-kotlin-qa:0.78.0"
multiJvmTesting = "org.danilopianini.multi-jvm-test-plugin:3.2.2"
publishOnCentral = "org.danilopianini.publish-on-central:7.0.4"
taskTree = "com.dorongold.task-tree:4.0.0"
